compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  local-pkg@*:
    dependencies:
      happy-dom: ^12.5.0
  styled-components@*:
    dependencies:
      react-is: "*"
yarnPath: .yarn/releases/yarn-4.1.0.cjs
