compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  styled-components@*:
    dependencies:
<<<<<<< main
      react-is: "*"

yarnPath: .yarn/releases/yarn-4.1.0.cjs
=======
      happy-dom: ^12.5.0
>>>>>>> fix :: 코멘트 반영
